service: newproject
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 128
  region: us-east-1
functions:
  hello:    
    handler: handler.hello
    environment:
      NAME: SAVITH
    events:
      - http:
          path: echo/hello
          method: get